### ISSUE TITLE
Convert input data to JSON

### ISSUE THREAD

**Issue by MatBenfield** [TheChelsOrg/club_finances#12]
convert data from hard-coded values in the tables and charts - move the data to a JSON file and then read this in to populate the data. Although this is a simple HTML + JavaScript page separating data and UI would help with contributors keeping the data up to date.

**Comment by NirmalKumarJoshi** [comment]
Hey @MatBenfield I would like to work on this issue.

**Comment by MatBenfield** [comment]
That would be great. Create a branch and have a go, then create a pull request when you are done. If you need any help do let me know. :)

**Comment by NirmalKumarJoshi** [comment]
Hey @MatBenfield , I have done the created JSON for tables. But I am not able to push the branch to this repo. It is saying permission denied.

**Comment by MatBenfield** [comment]
@NirmalKumarJoshi  I've invited you to be a collaborator on the repo. Thanks 👍
