### ISSUE TITLE
Adding responsive navigation bar to the site

### ISSUE THREAD

**Issue by NirmalKumarJoshi** [TheChelsOrg/club_finances#15]
**Is your feature request related to a problem? Please describe.**
No, this would be a feature.

**Describe the solution you'd like**
Currently, the site does not have a proper navigation bar at the top, having one will improve the look and feel of the page.

**Describe alternatives you've considered**
Not currently.

**Additional context**
We can use Bootstrap to have a navigation bar.

**Comment by NirmalKumarJoshi** [comment]
I would like to work on it. Please assign this to me.

**Comment by MatBenfield** [comment]
Thanks, I really like the flot charts and the tablesorter, but the rest of the UI could do with an update. Bootstrap might be a little overkill (its quite large), but happy for you to put something together, perhaps another light weight framework?

**Comment by NirmalKumarJoshi** [comment]
We can use [Semantic UI](https://semantic-ui.com/) as an alternative of Bootstrap. Please suggest!

**Comment by MatBenfield** [comment]
Semantic UI sounds good to me! thank you so much :-)
