### ISSUE TITLE
Tablesorter conflicts have stopped it from working

### ISSUE THREAD

**Issue by MatBenfield** [TheChelsOrg/club_finances#18]
Javascript plugins should be enabled on the two tables, allowing sorting and zebra style highlighting/style for each row.
This is currently not working and the console is reporting issues with the JavaScript.

**Comment by NirmalKumarJoshi** [comment]
Will look into it @MatBenfield . Please assign this to me.

**Comment by MatBenfield** [comment]
Would you be ok to replace all the H2 headings with something nicer looking too?

also do you have a PayPal account at all?

**Comment by NirmalKumarJoshi** [comment]
Yeah sure @MatBenfield I will make the heading changes accordingly, can you please create a seprate issue for the same. This will help in keeping the track of ToDo's.

Yes I have a PayPal account.

**Comment by MatBenfield** [comment]
Will do. Thanks,

Could you send me an email with your account email to  club_finance@thechels.uk please :-)

**Comment by NirmalKumarJoshi** [comment]
Just sent the mail. Please confirm if you recieved it. :)

**Comment by MatBenfield** [comment]
I have thanks, it seems like your account cannot receive anything at the moment though.

**Comment by NirmalKumarJoshi** [comment]
Hey @MatBenfield . I am not the currency you are transferring to the account. I just added British Pound to it.
Please try now.

**Comment by MatBenfield** [comment]
I've tried rupees and GBP, but says your account cannot accept payments, or gifts either. :-(

**Comment by NirmalKumarJoshi** [comment]
Yeah @MatBenfield it will be rupees. Can you mail me your email linked to your your account so that I can request through PayPal. I have changed few settings I hope it works now.
Please try once more.

**Comment by NirmalKumarJoshi** [comment]
Sorry for the inconvenience @MatBenfield . I just confirmed my account on PayPal and received a mail that now I can receive payments from abroad.

Please can you try it now. :)

**Comment by MatBenfield** [comment]
Success! 👍
